name: buildAssist
main: com.github.unchama.buildassist.BuildAssist
version: 0.0.19

commands:
  fly:
      description: This is a fly command.
      usage: /<command> <finish/amount/endless>
      permission-message: You don't have <permission>
      permission: multibuildplugin.build

  wand:
      description: This is a wand command.
      usage: /<command> <set/help>
      permission-message: You don't have <permission>
      permission: multibuildplugin.wand
